### ISSUE TITLE
Pytorch 1.3.1 version does not exist on the official website, how to install Pytorch 1.3.1 separately？

### ISSUE THREAD

**Issue by zhouhao-learning** [MolecularAI/Reinvent#11]
Hello, I am running `conda env create -f reinvent_shared.yml`, because of my network problem, there is a problem with the installation of pytorch, so I want to execute `pip install pytorch==1.3.1` alone, but the system prompts no Found that `pytorch==1.3.1`, and then I checked on the pytorch official website, I did not find pytorch 1.3.1 version, so I want to confirm whether there is a version error in the environment you provide?

**Comment by patronov** [comment]
Hi, There is no version error in the environment specs since they are automatically generated.
I believe pytorch 1.2 should work just as fine with the current code:
conda install pytorch==1.2.0 torchvision==0.4.0 cudatoolkit=10.0 -c pytorch
You might need to adjust the version according to the cuda drivers you are using.
Here are some installation hints with conda. 
https://pytorch.org/get-started/previous-versions/
You could also try the latest pytorch versions but we havent tested it on this branch.

**Comment by zhouhao-learning** [comment]
> Hi, There is no version error in the environment specs since they are automatically generated.
> I believe pytorch 1.2 should work just as fine with the current code:
> conda install pytorch==1.2.0 torchvision==0.4.0 cudatoolkit=10.0 -c pytorch
> You might need to adjust the version according to the cuda drivers you are using.
> Here are some installation hints with conda.
> https://pytorch.org/get-started/previous-versions/
> You could also try the latest pytorch versions but we havent tested it on this branch.



ok, I will try to run on pytorch 1.2 version, if there is an error I will inform you.
In addition, why do you not support tensorflow 2.0 or Keras, this may be easier to get started

**Comment by zhouhao-learning** [comment]
@patronov

**Comment by patronov** [comment]
While Keras is a convenient library for prototyping and comes with a lot of out-of-the box options it can also introduce limitations for long term development. We find pytorch to be offering sufficient flexibility without imposing any constraints. Also if you are looking to get started with running REINVENT, please have a look at [this repository](https://github.com/MolecularAI/ReinventCommunity) where we provide a number of examples.
