### ISSUE TITLE
Are there any groups or organizations that communicate

### ISSUE THREAD

**Issue by zhouhao-learning** [MolecularAI/Reinvent#14]
Hello, I often encounter a lot of unclear problems when reproducing your results, but it is not a bug in the code, so I want to know if you have a group or organization for communicating problems. If you don’t understand the problem, you can promptly Q&A?

If not, I think there is a very good idea, which can attract more people to understand this project, and it is very convenient for you to promote. What do you think?

**Comment by patronov** [comment]
Hi, Unfortunately there is no dedicated mailing list or a Q&A forum for discussions around de novo design or related topics with the community.
Maybe @EBjerrum might be able to share better insight on this.
Otherwise, it is a nice idea and if you have any ideas or suggestions for suitable platforms we are open to consider.
