### ISSUE TITLE
Will more scoring functions be added in the future?

### ISSUE THREAD

**Issue by JinChengneng** [MolecularAI/Reinvent#15]
Hi there, I've used ```Reinvent``` in recent days and generated some interesting molecules. Thanks a lot for your efforts!
However, I've found that the scoring functions are still limited and more scoring functions are desired, for example, ```logP``` and ```H-Acceptors```. I would appreciate it if you could add more frequently used scoring functions in the near future.

**Comment by CMargreitter** [comment]
Thanks for you interest! I'm glad you used REINVENT to some effect so quickly!

As for your question, we are continuously implementing new components and will release them after thorough testing. For example we are currently working on docking and pharmacophore searches in order to bring 3D / structural information in as well. But we're also happy to consider new components suggested by the community, so if you have any specific ideas please let us know (we'll discuss H-bond acceptors internally, but I think we can add them very soon).

**Comment by JinChengneng** [comment]
Thanks for your high attention to the community. I'm so glad that you would take H-bond acceptors into your consideration. How about ```logP```? I think it's also a frequently used property.

**Comment by CMargreitter** [comment]
Just pushed the HBA (Lipinski) component. There's an example in the `data/examples/templates/reinforcement_learning_all_components.json`, but it is very similar to the HBD one.

> How about logP? I think it's also a frequently used property.

True that, will look into it as well.

**Comment by CMargreitter** [comment]
Also added a new SLogP component, again have a look at the `data/examples/templates/reinforcement_learning_all_components.json` file.

**Comment by JinChengneng** [comment]
Great! I'll check it and thanks for your efforts.

**Comment by CMargreitter** [comment]
No worries! Would you mind giving me some feedback on whether it works?

**Comment by JinChengneng** [comment]
Sure, I will try it next week. If anything goes wrong, I will create new issues. I hope we can do together to make ```Reinvent``` get better.
