### ISSUE TITLE
Train a new model with a new .smi set

### ISSUE THREAD

**Issue by Gromax13** [MolecularAI/Reinvent#20]
Hi,

Thanks again for developing this wonderful tool.
I'm trying to train a new model with a set of smiles of interest. First of all I create a new model and then train it with a TL run.
I managed to do that with your original chembl training set without any problems, but trying with other training sets and using the same protocol always gives me this type of error:

`  File "/progs/all/opensource/reinvent/0.0_2020.09.14_9c57636/source/input.py", line 25, in <module>
    main()
  File "/progs/all/opensource/reinvent/0.0_2020.09.14_9c57636/source/input.py", line 21, in main
    manager.run()
  File "/cluster/import/master/progs/all/opensource/reinvent/0.0_2020.09.14_9c57636/source/running_modes/manager.py", line 95, in run
    job()
  File "/cluster/import/master/progs/all/opensource/reinvent/0.0_2020.09.14_9c57636/source/running_modes/manager.py", line 41, in _run_transfer_learning
    runner.run()
  File "/cluster/import/master/progs/all/opensource/reinvent/0.0_2020.09.14_9c57636/source/running_modes/transfer_learning/transfer_learning_runner.py", line 29, in run
    self._train_epoch(epoch, self._config.input_smiles_path)
  File "/cluster/import/master/progs/all/opensource/reinvent/0.0_2020.09.14_9c57636/source/running_modes/transfer_learning/transfer_learning_runner.py", line 38, in _train_epoch
    for _, batch in enumerate(self._progress_bar(data_loader, total=len(data_loader))):
  File "/progs/all/opensource/reinvent/0.0_2020.09.14_9c57636/miniconda3/lib/python3.7/site-packages/tqdm/std.py", line 1091, in __iter__
    for obj in iterable:
  File "/progs/all/opensource/reinvent/0.0_2020.09.14_9c57636/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/progs/all/opensource/reinvent/0.0_2020.09.14_9c57636/miniconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/progs/all/opensource/reinvent/0.0_2020.09.14_9c57636/miniconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/cluster/import/master/progs/all/opensource/reinvent/0.0_2020.09.14_9c57636/source/models/dataset.py", line 22, in __getitem__
    encoded = self._vocabulary.encode(tokens)
  File "/cluster/import/master/progs/all/opensource/reinvent/0.0_2020.09.14_9c57636/source/models/vocabulary.py", line 59, in encode
    vocab_index[i] = self._tokens[token]
KeyError: '7'
^M 69%|######8   | 7798/11350 [04:31<02:03, 28.77it/s]
`
It doesn't stop always at the same point and also the key error is not always the same (sometimes is KeyError: '%15' or KeyError: '%19'). It would assume that is related to the training set. I tried to pre process all the smiles with rdkit, retaining only the atom types you use in the original publication (['H','B','C','N','O','F','S','Cl','Br']) and also using 'isomericsmiles=False' but this doesn't solve the problem unfortunately.

Thanks in advance for your help,

Cheers

**Comment by patronov** [comment]
Hi, thank you for using Reinvent!
Yes this is an issue as we dont currently provide a standardizer that would help you to sanitize the dataset you want to conduct TL with. 
We intend to do so in the future but for now it would involve a bit of a manual effort from your end. 
From your comment I can see Boron in your allowed types (['H','**B**','C','N','O','F','S','Cl','Br']) . This isnt used for training the prior we provide. Perhaps this is the source of the error?
Alternatively, we have a [workflow ](https://github.com/MolecularAI/ReinventCommunity/blob/master/notebooks/Data_Preparation.ipynb)for purging the data for training a prior. That might also help if you apply the rules on your TL dataset.

**Comment by rajiv03** [comment]
I would like to make a use of this tool for following scenarios: 
(1) I would like to train a model with my compounds smiles and get few novel scaffolds (exploration) and optimize the lead compounds (exploitation). 

(2) I would like to generate a molecule that are very favorable/selective to one target?

I tried Create_Model_Demo.ipynb workflow with these ~500 compounds and generated model.ckpt. Next I used TL with model.ckpt and few active compounds as inputs. However, the results I'm getting from the sampling and Reinforcement_Learning_Exploration worflow are completely incorrect smiles. i.e., 4-=F)5c()cnc)(3235(c(2)C(cc

My main confusion in your worflow is : Once we create a model(.ckpt) in Create_Model_Demo.ipynb where we use them?
For training in TL , the input model mentioned as "random.prior.new" where they comes from? and output model "focused.agent", where we use them?
Again in RF, input models, prior and agent,  "random.prior.new" were used, why is that?


I would appreciate what is the approrpate way to achive this. Thanks

**Comment by GuoJeff** [comment]
Hi @rajiv03,

Thank you for your interest in REINVENT.

The Create_Model_Demo is meant to train a model, denoted the "Prior", which learns the SMILES syntax. In order to learn the syntax well, a larger dataset should be used. The provided "random.prior.new" is a "Prior" that has been trained on the ChEMBL dataset composed of over 1 million molecules. A possible solution to (1) is to use the  "random.prior.new" provided and perform transfer learning on it using your dataset of ~500 compounds to focus the prior (the outputted model can be used as the new prior). Alternatively, you could use the "random.prior.new" as provided and train a predictive model (such as a RF) using your compounds and provide the resulting surrogate model as a component to the scoring function of REINVENT. Using reinforcement learning, the model should gradually learn to generate molecules that satisfy the surrogate model built with your compounds.

In regards to why the prior and the agent both use "random.prior.new" in the example notebook, it is because the agent is first initialized to be the same as the prior. The purpose of this is so the agent also knows how to generate valid SMILES. Over the course of reinforcement learning, the agent is updated such that it retains its ability to generate valid SMILES while gradually generating molecules that increasingly satisfy your desired objective (as specified via the Scoring Function).

Please let me know if this answers your questions.
