### ISSUE TITLE
Reinforcement learning, generating invalid molecules resulting assertion error and it is failing the entire process.

### ISSUE THREAD

**Issue by arijit-s** [MolecularAI/Reinvent#44]
I have came across an frequent issues, where the reinforcement learning process is generating an molecule which rdkit considers as invalid molecule.
As a result some time I am getting 

1. Assertion Error from [this](https://github.com/MolecularAI/reinvent-scoring/blob/main/reinvent_scoring/scoring/function/base_scoring_function.py#L27) place 
or 
2. Math domain error when I am using custom product from [this](https://github.com/MolecularAI/reinvent-scoring/blob/main/reinvent_scoring/scoring/function/custom_product.py#L17) line

The above issues terminate the entire process, although it is due to only one single invalid molecule

My question is 

1. Is there any solution to prevent generating invalid molecule (as per rdkit)
2. If an invalid molecule is generated how can we remove it from the batch, or how can we skip the step and move to next step? So the entire process does not fail due to one single invalid molecule?

**Comment by halx** [comment]
Sorry for the very late reply but I have taken over the project just recently.

We are currently rewriting the software so we would also fix you problem.  Invalid molecules are, unfortunately, generated occasionally and is in the nature of how the algorithm works.  However, the software should automatically disregard invalid SMILES.  I guess that the the real issue here is the two errors you report.  They shouldn't happen are therefore most likely a bug.
