### ISSUE TITLE
Conda env create fails on Windows/Mac

### ISSUE THREAD

**Issue by tblaschke** [MolecularAI/Reinvent#5]
Hey,

conda can't solve the dependencies for non-linux platforms. This is because the packages in `reinvent-shared.yml` contain build strings. 
The easiest fix is to use the `--no-build` flag when exporting the environment.
However, for long-term support, it might be beneficial to create minimal `reinvent-minimal.yml`, which only contains the explicitly needed dependencies and not the dependencies of our dependencies. 

\Thomas

**Comment by patronov** [comment]
Hi,

Good point, although I'm not sure why would anyone run it under windows. Development maybe? 
Anyway, I accepted the minimal environment but I fear there might be still packages missing. XGboost for instance. We had to reduce the code for the public release since there are features irrelevant to the broad audience and there are features that will be released later on. That is why there are so many packages in the environment. Likely some of those will be needed for future releases (OpenEye library for eg.).

Best,

Atanas
