### ISSUE TITLE
error while running Lib-Invent

### ISSUE THREAD

**Issue by arvindsemwal20** [MolecularAI/Reinvent#52]
Hi, I got the following issue, during running of the this Jupyter Notebook Lib-INVENT RL1 - QSAR.ipynb under the https://github.com/MolecularAI/Lib-INVENT/tree/main/tutorial

I have created the envs for Lib-Invent and installed all the packages from https://github.com/MolecularAI/Lib-INVENT/blob/main/environment.yml

I have also attached the *.json file, which i used.

Can you please help me out.

[RL_input.json.zip](https://github.com/MolecularAI/Reinvent/files/11512111/RL_input.json.zip)

Traceback (most recent call last):
  File "/media/medicina/ReinventCommunity/notebooks/Lib-INVENT/input.py", line 20, in <module>
    manager.run()
  File "/media/medicina/ReinventCommunity/notebooks/Lib-INVENT/running_modes/manager.py", line 81, in run
    job()
  File "/media/medicina/ReinventCommunity/notebooks/Lib-INVENT/running_modes/manager.py", line 51, in _reinforcement_learning
    reinforcement_learning.run()
  File "/media/medicina/ReinventCommunity/notebooks/Lib-INVENT/running_modes/reinforcement_learning/reinforcement_learning.py", line 43, in run
    actor_nlls, critic_nlls, augmented_nlls = self._updating(sampled_sequences, score_summary.total_score)
  File "/media/medicina/ReinventCommunity/notebooks/Lib-INVENT/running_modes/reinforcement_learning/reinforcement_learning.py", line 59, in _updating
    actor_nlls, critic_nlls, augmented_nlls = self.learning_strategy.run(scaffold_batch, decorator_batch, score, actor_nlls)
AttributeError: 'NoneType' object has no attribute 'run'

**Comment by halx** [comment]
Hi,

many thanks for your interest in REINVENT.

I think the issue here is that you are using an old repository that has been prepared for a particular publication.  This repository is not maintained anymore.  What you should be using instead, for the moment at least, is https://github.com/MolecularAI/Reinvent which is the current release 3.2 and also incorporates the Libinvent code.  Supporting notebooks are in https://github.com/MolecularAI/ReinventCommunity/.

We are currently preparing a new release which we hope to release later this year.

If you have any further questions,, please let us know.

Many thanks,
Hannes.

**Comment by VirtualChemist** [comment]
Thank you so much for the reply.

I saw the tutorial on Lib-Invent in main Repository of ReinventCommunity. That is great tutorial on use case for Lib-Invent.

I have few additional question, I will be very happy if you help us.

I am preparing new trained model for Lib-Invent based on our new data, which is not a small molecule dataset.

1. Can I use this [reaction_based_slicing.ipynb](https://github.com/MolecularAI/Lib-INVENT-dataset/blob/main/tutorial/reaction_based_slicing.ipynb) tutorial to prepare the sliced data.
2. To create the empty.prior on my new data. Is this tutorial https://github.com/MolecularAI/ReinventCommunity/blob/master/notebooks/Create_Model_Demo.ipynb can help us, even our input smiles are not small molecules. Because there are certain parameters, which required to be adjusted to create an empty.prior model according to my new data.

configuration["parameters"] = {
    "output_model_path": output_model_path,
    "input_smiles_path": input_SMILES_path,
    "num_layers": 3,
    "layer_size": 512,
    "cell_type": "lstm",
    "embedding_layer_size": 256,      
    "dropout": 0.,
    "max_sequence_length": 256,
    "layer_normalization": False,
    "standardize": False
  }

Thanks,

**Comment by arvindsemwal20** [comment]
Thank you so much for the reply.

I saw the tutorial on Lib-Invent in main Repository of ReinventCommunity. That is great tutorial on use case for Lib-Invent.

I have few additional question, I will be very happy if you help us.

I am preparing new trained model for Lib-Invent based on our new data, which is not a small molecule dataset.

Can I use this reaction_based_slicing.ipynb tutorial to prepare the sliced data.
To create the empty.prior on my new data. Is this tutorial https://github.com/MolecularAI/ReinventCommunity/blob/master/notebooks/Create_Model_Demo.ipynb can help us, even our input smiles are not small molecules. Because there are certain parameters, which required to be adjusted to create an empty.prior model according to my new data.
configuration["parameters"] = {
"output_model_path": output_model_path,
"input_smiles_path": input_SMILES_path,
"num_layers": 3,
"layer_size": 512,
"cell_type": "lstm",
"embedding_layer_size": 256,
"dropout": 0.,
"max_sequence_length": 256,
"layer_normalization": False,
"standardize": False
}

Thanks,

**Comment by halx** [comment]
I am not sure what you mean by not small molecule.  REINVENT models are certainly based on language models but the tokenizer expects to work on SMILES.  

The slicing will depend on your particular use case.   The original LibInvent paper describes this in some detailf for the dataset chosen at that time.

Yes, you have to start with an "empty" model which basically defines the hyperparameters of the RNN and also computes all possible tokens from your dataset.  You may want to experiment with hyperparamters to find the ideal set for your application.

@jiazhenhe would you have any suggestions?

**Comment by arvindsemwal20** [comment]
Thank you for the detailed information.

Actually, my inputs are peptide smiles, which are larger than small molecules, thus we expect change in configuration parameters for empty model creation.

configuration["parameters"] = {
"output_model_path": output_model_path,
"input_smiles_path": input_SMILES_path,
"num_layers": 3,
"layer_size": 512,
"cell_type": "lstm",
"embedding_layer_size": 256,
"dropout": 0.,
"max_sequence_length": 256,
"layer_normalization": False,
"standardize": False
}

So I expect the max_sequence_length has to be changed to fit the peptide length, if the length exceed 256.
This notebook was specifically designed to create empty model for small. 
https://github.com/MolecularAI/ReinventCommunity/blob/master/notebooks/Create_Model_Demo.ipynb
So, I just wanted to if this notebook will also work for empty model creation for peptide-smiles in Lib-Invent prior training, if the configuration parameters are changed.

Thanks,

**Comment by halx** [comment]
max_sequence_length determines the maximum number of allowed tokens.  For standard chemistry including peptides that should be more than enough.

Yes, that notebook should get you started.

**Comment by arvindsemwal20** [comment]
Thank you for your helpful comments.
